files:
  - source: /**/**/**/values/custom_strings.xml
    translation: /%original_path%-%android_code%/%original_file_name%
  - source: /**/SettingsLib/**/values/evolution_strings.xml
    translation: /%original_path%-%android_code%/%original_file_name%
  - source: /**/**/res-keyguard/values/evolution_arrays.xml
    translation: /%original_path%-%android_code%/%original_file_name%
